### ISSUE TITLE
数据集处理问题

### ISSUE THREAD

**Issue by lsqzs** [QinHsiu/MCLRec#2]
您好,最近在跑一些基线的数据, 想问下你们的数据集是怎么预处理的, 因为和recbole的不同,希望能告知下感谢

**Comment by QinHsiu** [comment]
你好，非常感谢你对我们工作的关注，就是我们数据预处理方式也是使用了RecBole的数据处理方式的，具体链接如下：https://github.com/RUCAIBox/RecSysDatasets
然后我们根据item的frequence对item id进行了重新编码，就是在RecBole的训练框架里面也是有这种处理机制的，你可以尝试在forward那里打印出来看一下，就是他也是对id进行了重新映射，另外为了实验公平性，我们还参考了https://github.com/salesforce/ICLRec/tree/master/data
的处理方法，最终发现经过Recbole框架得到的序列的id与ICLRec这个是一致的，保证了实验的公平性（max item是一致的，交互的item数目也是一致的，稀疏性也是一样的），你可以直接使用RecBole那个数据处理的代码，然后需要按timestamp排序并去除掉少于5个交互的数据（item和user），然后直接使用MCLRec运行即可。希望能够帮助到你。

**Comment by lsqzs** [comment]
非常感谢你们杰出的工作, 我们之前在RecSysDatasets的确找到了你们数据集未处理的recbole版本, 但是在Yelp数据集上我们一直未找到对应版本, 不知可否提供一下. 这是我的邮箱lsq111222l@gmail.com

**Comment by QinHsiu** [comment]
因为大部分baseline模型都是使用的第二个链接的预处理数据集进行训练的，因此为了更加公平的进行比较，我们参考了第一个链接和https://github.com/RuihongQiu/MMInfoRec/blob/master/data/data_process.py
这个链接提供的数据处理的代码对原本的txt中的数据进行了预处理（这里已经按照时间进行排序了，因此我们直接设置timestamp一列为0），预处理之后的数据已经发送到您的邮箱了，这个处理的数据主要是用于跑DuoRec这个baseline模型。最后非常感谢您对我们工作的关注！

**Comment by OKAKIL** [comment]
您好，非常感谢你们的开源，有的模型需要带时间戳信息，能否麻烦提供一下你们原文中三个数据集带时间戳的原子文件吗？我的邮箱664972@qq.com。如果能提供，非常感谢🙇‍。
