### ISSUE TITLE
模型预估问题

### ISSUE THREAD

**Issue by gqlxj1987** [QinHsiu/MCLRec#3]
你好，
1. 这边在做这部分工程试验，想应用到召回场景，是否可行？
2. 如果可行的话，要对model部分进行predict的话，该部分input参数如何来确定？
3. 是否这部分工作可以取代itemCF的召回？

谢谢

**Comment by QinHsiu** [comment]
你好，
  1.非常感谢你对我们工作的关注，针对第一个问题，我们的工作主要是针对召回任务的，所以是可行的；
  2.不知道我理解对不对，你是问关于模型参数如何优化的，这里是采用随机数据增强+可学习的模型增强来做的，使用元更新策略，也即两阶段更新方法来优化编码器与模型增强器的参数的；
  3.这部分工作可以作为ItemCF召回的补充，现在落地应用中一般都采用多路召回策略，因此可以将我们提出的方法作为其他召回方法的补充；
不客气，有问题欢迎讨论！

**Comment by gqlxj1987** [comment]
关于第二个问题，说明一下：
是指模型在做批量预估的时候，有看到有用到recbole的full_sort_scores方式，但这部分的输入还是user_id，不是很理解，如果作为itemCF的补充的话，input是否应该是item_id？

**Comment by OKAKIL** [comment]
你好，请问你公式（8）嵌入向量和编码向量作对比损失是一样的吗？
还有那个预测损失，意思就是假如召回5，就用softmax概率最高的5个item作为推荐吗？
如果用交叉子序列相同item作元优化对比学习损失会比本文性能高吗？

**Comment by QinHsiu** [comment]
> 关于第二个问题，说明一下： 是指模型在做批量预估的时候，有看到有用到recbole的full_sort_scores方式，但这部分的输入还是user_id，不是很理解，如果作为itemCF的补充的话，input是否应该是item_id？

你好，就是因为做的任务是序列推荐，输入的是序列，是item id组成的序列，item CF/User CF本质都是协同过滤，最终目的还是根据给定的用户交互数据来预测他可能交互的下一个商品，因此我的意思是可以把MCLRec最后的针对每个用户的预测的结果作为最终召回层得到的所有召回商品候选集的一个补充。

**Comment by QinHsiu** [comment]
> 你好，请问你公式（8）嵌入向量和编码向量作对比损失是一样的吗？ 还有那个预测损失，意思就是假如召回5，就用softmax概率最高的5个item作为推荐吗？ 如果用交叉子序列相同item作元优化对比学习损失会比本文性能高吗？

你好，问题1：所有对比损失都是用的infoNCE对比损失函数；问题2：是的，就是取了softmax之后取top5的item作为推荐；问题3：两篇文章解决的点不一样，交叉子序列是为了提取意图监督信号，主要是为了后面聚类；元优化对比学习主要是利用可学习的模型增强器来提取信息含量更加丰富的特征用于对比学习，这里我们没有做此类尝试，你可以尝试结合看看效果！

**Comment by gqlxj1987** [comment]
> > 关于第二个问题，说明一下： 是指模型在做批量预估的时候，有看到有用到recbole的full_sort_scores方式，但这部分的输入还是user_id，不是很理解，如果作为itemCF的补充的话，input是否应该是item_id？
> 
> 你好，就是因为做的任务是序列推荐，输入的是序列，是item id组成的序列，item CF/User CF本质都是协同过滤，最终目的还是根据给定的用户交互数据来预测他可能交互的下一个商品，因此我的意思是可以把MCLRec最后的针对每个用户的预测的结果作为最终召回层得到的所有召回商品候选集的一个补充。

如果输入是用户序列话，新用户就无法用到这个推理；同时，基于item id序列推理是不是也没办法做

**Comment by OKAKIL** [comment]
关于问题1补充：公式（8）是对公式（7）的解释，公式（8）你为什么用增强视图的嵌入X1,X2，而不用公式（7）中的h1,h2那？
非常感谢你的回复。

**Comment by QinHsiu** [comment]
> 关于问题1补充：公式（8）是对公式（7）的解释，公式（8）你为什么用增强视图的嵌入X1,X2，而不用公式（7）中的h1,h2那？ 非常感谢你的回复。

你好，这里是为了复用公式，也即后面在计算基于模型增强视图对比学习损失的时候可以直接使用公式(8)。
